### ISSUE TITLE
Highlight relevant chunks on the PDF

### ISSUE THREAD

**Issue by ChakshuGautam** [ChatWithPDF/app#2]
```json
{
  "chunks": [
    {
      "start": 234,
      "end": 567,
      "page": 24,
      "text": "..."
      
    }
  ]
}
```

- [x] @prtkjakhar the relevant ticket
- [ ] Backup - take them to the relevant page

**Comment by prtkjakhar** [comment]
Raised this ticket: https://github.com/react-pdf-viewer/react-pdf-viewer/issues/1571
PDF viewer website: https://react-pdf-viewer.dev/
